#!/usr/bin/env python3

import sys

def generate_source(name: str, data: bytes) -> str:
	output = f"// Automatically generated by {sys.argv[0]} from {sys.argv[1]}\n\n#include <stdint.h>\n\nconst uint8_t {name}_data[{len(data)}] = {{\n"

	for y in range(0, len(data), 16):
		output += "\t"
		for x in range(min(16, len(data)-y)):
			output += f"0x{data[x+y]:02x}, "
		output += "\n"
	
	output += "};\n"

	return output

def generate_header(name: str, data: bytes) -> str:
	return f"// Automatically generated by {sys.argv[0]} from {sys.argv[1]}\n\n#include <stdint.h>\n\n#define {name.upper()}_DATA_LENGTH {len(data)}\n\nextern const uint8_t {name}_data[{len(data)}];\n"

if __name__ == "__main__":
	
	if len(sys.argv) != 4:
		print(f"Usage: {sys.argv[0]} binary out_c out_h")
		exit(1)
	
	name = sys.argv[1][sys.argv[1].rfind("/")+1:sys.argv[1].rfind(".")]

	data = open(sys.argv[1], "rb").read()

	source = generate_source(name, data)
	header = generate_header(name, data)

	open(sys.argv[2], "w").write(source)
	open(sys.argv[3], "w").write(header)
