/*

 TESTMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 24
   Tile set      : C:\Users\07alab19\Documents\programming\pgm2-gb-zombie\resrc\tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __testmap_h_INCLUDE
#define __testmap_h_INCLUDE

#define testmapWidth 32
#define testmapHeight 24
#define testmapBank 0

extern const unsigned char testmap[];

#endif

/* End of TESTMAP.H */
