#include <gb/gb.h>

#ifndef _defines_h_INCLUDE
#define _defines_h_INCLUDE


#define BUFFER_WIDTH DEVICE_SCREEN_BUFFER_WIDTH
#define BUFFER_WIDTH_2 (DEVICE_SCREEN_BUFFER_WIDTH/2)

#define BUFFER_HEIGHT DEVICE_SCREEN_BUFFER_HEIGHT
#define BUFFER_HEIGHT_2 (DEVICE_SCREEN_BUFFER_HEIGHT/2)

#define SCREEN_WIDTH DEVICE_SCREEN_WIDTH
#define SCREEN_WIDTH_2 (DEVICE_SCREEN_WIDTH/2)

#define SCREEN_HEIGHT DEVICE_SCREEN_HEIGHT
#define SCREEN_HEIGHT_2 (DEVICE_SCREEN_HEIGHT/2)


#endif // _defines_h_INCLUDE
